### ISSUE TITLE
执行test文件报错

### ISSUE THREAD

**Issue by yueminghai** [CN-TU/machine-learning-in-ebpf#2]
root@f46c2947a9da:/machine-learning-in-ebpf# python3 test.py --run_scenario just_one_flow
Traceback (most recent call last):
  File "/machine-learning-in-ebpf/test.py", line 15, in <module>
    import virtnet
  File "/usr/local/lib/python3.9/dist-packages/virtnet/__init__.py", line 9, in <module>
    from . host import Host, PhysicalHost, Router
  File "/usr/local/lib/python3.9/dist-packages/virtnet/host.py", line 16, in <module>
    from pyroute2.netns.nslink import NetNS
ModuleNotFoundError: No module named 'pyroute2.netns.nslink'

**Comment by muxamilian** [comment]
Sorry, I don't speak Chinese, so I can only guess what you wrote in the title. 

It seems like you're using Python 3.9 which is unfortunately not supported (see the README). If you want to try out this repo, I suggest you use Docker and install Python 3.7 in Docker.
